const ip = '';
const ACCESS_TOKEN_KEY = 'ACCESS_TOKEN';
const REFRESH_TOKEN_KEY = 'REFRESH_TOKEN';
const DEFAULT_PADDING_H = 24.0;
const DEFAULT_WIDGET_PADDING = 10.0;
const JOB_SEARCH_KEY = 'JOB_SEARCH_KEY';
const RESERVATION_SEARCH_KEY = 'RESERVATION_SEARCH_KEY';
const BUTTON_HEIGHT = 45.0;